### ISSUE TITLE
After sharing to QQ, cannot go back to APP

### ISSUE THREAD

**Issue by samueljess** [floatinghotpot/cordova-plugin-qq#2]
Once I've shared an article to QQ, the button to get back to our app does not work. Any idea how to fix?

**Comment by floatinghotpot** [comment]
You need get a valid app key for your app from Tencent

**Comment by samueljess** [comment]
We do have a valid app key from Tencent being used.

**Comment by floatinghotpot** [comment]
Then what's the behavior?

**Comment by samueljess** [comment]
Sorry for the late reply, we found the issue was that we had not removed the default app key in your plugin. Thanks for your quick replies!
